//
//  Constants.swift
//  Perfect Green Screen
//
//  Created by Vitaly Bokser on 4/2/19.
//  Copyright © 2019 Vitaly Bokser. All rights reserved.
//

import Foundation

let DEFAULT_HISTOGRAM_VISIBLE_STRING = "DEFAULT_HISTOGRAM_VISIBLE_STRING"
let DEFAULT_HISTOGRAM_BANDS_VISIBLE_STRING = "DEFAULT_HISTOGRAM_BANDS_VISIBLE_STRING"

let DEFAULT_MAX_BANDS_VALUE_INT:Int = 20
let DEFAULT_MAX_BANDS_VALUE_STRING:String = "20"

let DEFAULT_NUMBER_OF_MAX_BANDS_INT:Int = 50
let DEFAULT_NUMBER_OF_MIN_BANDS_INT:Int = 10
//let DEFAULT_NUMBER_OF_MAX_BANDS_STRING = "DEFAULT_NUMBER_OF_MAX_BANDS_STRING"

//var CURRENT_NUMBER_OF_MAX_BANDS_INT:Int = 20
let CURRENT_NUMBER_OF_MAX_BANDS_STRING = "CURRENT_NUMBER_OF_MAX_BANDS_STRING"

//var CURRENT_NUMBER_OF_BANDS_INT:Int = 10
let CURRENT_NUMBER_OF_BANDS_STRING = "CURRENT_NUMBER_OF_BANDS_STRING"

